### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by skrew** [draperlaboratory/fracture#45]
Hi, i have a core dump when i try to use it on a iOS app compiled with armv7, i don't know if it's working with iOS bin ?

```
0  fracture-cl     0x0000000001b150eb llvm::sys::PrintStackTrace(_IO_FILE*) + 38
1  fracture-cl     0x0000000001b15368
2  fracture-cl     0x0000000001b14d0d
3  libpthread.so.0 0x00007f16fccef340
4  fracture-cl     0x00000000009de01d
5  fracture-cl     0x00000000009dd6cf main + 463
6  libc.so.6       0x00007f16fbcedec5 __libc_start_main + 245
7  fracture-cl     0x00000000009db5b4
```

**Comment by rtc-draper** [comment]
What does it pop up as when you run “file” on it? Even if not recognized, the raw/dummy object file format should be defaulted to…

Can you run in a debugger and provide line information? What you have is the default stack trace and that’s not helpful. Note you’ll need to set your debugger to follow fork calls.

-R

**Comment by skrew** [comment]
```Mach-O universal binary with 1 architecture: [arm_v7: Mach-O arm_v7 executable]```

For the debugger, you mean on fracture-cl, not the ios binaries, right ?
Seem to have a problem while getting arch... but i pass -arch=arm 

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000009de01d in loadBinary (FileName=...) at fracture-cl.cpp:174
174	    TT.setArch(Triple::ArchType(TempExecutable->getArch()));
```
Don't know if you have enough information, i'm on linux and without xcode / ida ... i'm (near) lost ;)

**Comment by rtc-draper** [comment]
That’s enough.

This indicates it’s trying to set the target triple and causing llvm’s libraries to choke. It might be us, though…Can you give me a dummy MachO binary to play with (e.g., hello world?)--- then we can have a test case and get it working. TBH we’ve never tried it on iOS stuff, although in theory you should be able to open it in “raw” mode.

**Comment by skrew** [comment]
running with ```-arch=arm -triple=arm-unknown-unknown``` got a new error

```
#0  0x0000000000a05675 in fracture::Disassembler::Disassembler (this=0x2e0c8e0, NewMC=0x2e0d000, NewExecutable=0x0, NewModule=0x0, InfoOut=..., ErrOut=...) at Disassembler.cpp:31
#1  0x00000000009de388 in loadBinary (FileName=...) at fracture-cl.cpp:190
#2  0x00000000009dd6cf in main (argc=4, argv=0x7fffffffe318) at fracture-cl.cpp:844
```
Look like a bad new for me... Anyway, thanks

**Comment by rtc-draper** [comment]
For arm, typically you need to specify the attr version with “-mattr=v7” or the like. I’m not sure which attr is appropriate for iPhone HW.

Anyway, send us a sample and I’ll see what I can do to make it readable.

**Comment by rtc-draper** [comment]
Marking as bug for now. I'll ask around and see if someone can generate an iPhone example for us.

**Comment by skrew** [comment]
I can send to you the sample i use, tell me where to send you a (private) dropbox link... Also if you want a custom build from iOS i can make one for you.

**Comment by rtc-draper** [comment]
A "helloworld" program for iOS posted to github would be best.
